spring:
  application:
    name: 69chan

  data:
    mongodb:
      uri: ${MONGO_URI}
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DATABASE:0}
      timeout: 60000ms
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

  datasource:
    username: ${POSTGRE_DB_USERNAME}
    password: ${POSTGRE_DB_PASSWORD}
    url: "jdbc:postgresql://${POSTGRE_DB_HOST}:${POSTGRE_DB_PORT}/postgres?user=${POSTGRE_DB_USERNAME}&password=${POSTGRE_DB_PASSWORD}"
    driver-class-name: org.postgresql.Driver
    hikari:
      transaction-isolation:

  h2:
    console:
      enabled: false

  jackson:
    date-format: yyyy-MM-dd

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: com.congty9a4.backend.repository.PostgreFullTextSearchDialect
        show_sql: true

  sql:
    init:
      mode: never

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 0
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
app:
  swagger:
    server:
      url: ${SWAGGER_SERVER_URL:0.0.0.0}

# Storage Configuration
# Choose between 'gcs' (Google Cloud Storage) or 'cloudinary'
storage:
  provider: ${STORAGE_PROVIDER:cloudinary}

# gcs:
#   bucket-name: 69chan-dev-store-media-files
#   sub-directory: media

jwt:
  expiration:
    refresh: 2592000 # 30 days in seconds
    access: 43200
  secret: ${JWT_SECRET}

server:
  port: 8080

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

google:
  client-id: ${GOOGLE_CLIENT_ID}