spring:
  application:
    name: backend

  config:
    import: optional:file:.env[.properties]

  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: "jdbc:postgresql://${DB_HOST}:${DB_PORT}/postgres?user=${DB_USERNAME}&password=${DB_PASSWORD}"
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always

  cloud:
    gcp:
      project-id: first-project-444717
      credentials:
        location: classpath:gcs_credentials.json

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 0

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
gcs:
  bucket-name: 69chan-dev-store-media-files
  sub-directory: images